### ISSUE TITLE
Java Logging with Lambda and Log4j2 appender has a bug

### ISSUE THREAD

**Issue by karlroberts** [awsdocs/aws-lambda-developer-guide#31]
The Bug is that if you follow the instructions logging does not work instead you get 

```
2018-04-23 14:04:19,908 main ERROR Error processing element Lambda ([Appenders: null]): CLASS_NOT_FOUND
2018-04-23 14:04:19,926 main ERROR Unable to locate appender "Lambda" for logger config "root"
```
Many  requests on Stackoverflow suggest that people are having trouble with this.

I have fixed the issue in a Pull request here:- [PR #27]( https://github.com/awsdocs/aws-lambda-developer-guide/pull/27)  please merge it. thanks

**Comment by spaethp** [comment]
Fixed, thanks

**Comment by hongqijia** [comment]
But I still have this error with latest available version, 1.1.0, of com.amazonaws:aws-lambda-java-log4j2.  When will the new jar with this fix be available in public maven repository?

**Comment by bevin0708** [comment]
Same error with 1.2, had to revert to 1.0
